# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ckName(object):
    def setupUi(self, ckName):
        ckName.setObjectName("ckName")
        ckName.resize(715, 397)
        self.tableWidget = QtWidgets.QTableWidget(ckName)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 531, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton_2 = QtWidgets.QPushButton(ckName)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 320, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(ckName)
        self.commandLinkButton.setGeometry(QtCore.QRect(561, 47, 201, 51))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.checkBox = QtWidgets.QCheckBox(ckName)
        self.checkBox.setGeometry(QtCore.QRect(570, 110, 91, 19))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(ckName)
        QtCore.QMetaObject.connectSlotsByName(ckName)

    def retranslateUi(self, ckName):
        _translate = QtCore.QCoreApplication.translate
        ckName.setWindowTitle(_translate("ckName", "参赛名单"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ckName", "A"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ckName", "B"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ckName", "C"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ckName", "D"))
        self.pushButton_2.setText(_translate("ckName", "提交"))
        self.commandLinkButton.setText(_translate("ckName", "EXCEL导入"))
        self.checkBox.setText(_translate("ckName", "修改"))
